{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "editor.serviceAccountName" . }}
  labels:
{{ include "editor.labels" . | indent 4 }}
{{- end -}}
