apiVersion: v1
kind: Service
metadata:
  name: {{ include "editor.fullname" . }}-api
  labels:
{{ include "editor.labels" . | indent 4 }}-api
spec:
  type: {{ .Values.service.api.type }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "editor.name" . }}-api
    app.kubernetes.io/instance: {{ .Release.Name }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "editor.fullname" . }}-frontend
  labels:
{{ include "editor.labels" . | indent 4 }}-frontend
spec:
  type: {{ .Values.service.frontend.type }}
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "editor.name" . }}-frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
